local function step_install_globals()
    require("libs.math")
    require("libs.littleclass")
    require("libs.table_extensions")
    require("app.gameplay.constants")

    local druid = require("druid.druid")
    druid.register("text_size_follower", require("app.scripts.widgets.text_size_follower"))
end

local function step_load_config()
    local buskets_cfg = sys.load_resource("/app/resources/config_buskets.json")
    _G.config = {}
    _G.config.buckets = json.decode(buskets_cfg) --[[@as {weights: integer[], values: integer[], gradient: GradientConfig}]]
end

local function step_load_storage()
    local storage = require("app.scripts.storage")
    task.await(function (done)
        storage.init(done)
    end)
end
local service_consumables = require("app.scripts.consumables.service_consumables")
local function step_init_services()
    local n = #config.buckets.weights
    service_consumables.init()
    local service_game_path = require("app.gameplay.systems.service_game_path")
    service_game_path.build_graph(n)
    local service_game_grid = require("app.gameplay.systems.service_game_grid")
    service_game_grid.build(n)
    local service_sounds = require("app.scripts.service_sounds")
    service_sounds.init()
    local provider_bucket_color = require("app.gameplay.systems.buckets.provider_bucket_color")
    provider_bucket_color.build(n, config.buckets.gradient)
end

local monarch = require("monarch.monarch")
local function step_navigate()
    --initialize monarch
    task.delay(0)
    monarch.show("gameplay")
end



---@type function[]
local steps = {
    step_install_globals,
    step_load_config,
    step_load_storage,
    step_init_services,
    step_navigate
}

function init(self)
    require("libs.async")
    task.thread(function ()
        for i, func_bootstrap_step in ipairs(steps) do
            print("[Bootstrap] Executing step #"..i)
            func_bootstrap_step()
        end
    end)
end

function update(self, dt)
    service_consumables.update()
end